# Generated by Django 5.0.2 on 2024-03-10 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Matches",
            new_name="Match",
        ),
        migrations.AlterField(
            model_name="tournament",
            name="registration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 10, 17, 54, 0, 557941, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="tournament_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 10, 17, 54, 0, 558132, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
