# Generated by Django 5.0.2 on 2024-03-03 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_alter_tournament_registration_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="registration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 3, 9, 40, 55, 468414, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="tournament_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 3, 9, 40, 55, 468602, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
