# Generated by Django 5.0.2 on 2024-03-11 17:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_rename_matches_match_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="state",
            field=models.CharField(default="Andhra Pradesh", max_length=100),
        ),
        migrations.AlterField(
            model_name="match",
            name="match_number",
            field=models.CharField(default="1", max_length=100),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="registration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 11, 17, 12, 55, 53513, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="tournament_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 11, 17, 12, 55, 53689, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="utr_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.utrid",
            ),
        ),
    ]
