# Generated by Django 5.0.2 on 2024-03-13 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_customuser_state_alter_match_match_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamdetail",
            name="in_game_name",
            field=models.CharField(default="In Game Name", max_length=100),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="registration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 13, 15, 2, 43, 928692, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="tournament_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 13, 15, 2, 43, 928883, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
