# Generated by Django 5.0.2 on 2024-03-03 16:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_alter_tournament_registration_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="registration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 3, 16, 56, 5, 138890, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="tournament_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 3, 16, 56, 5, 139060, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="Matches",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "match_number",
                    models.CharField(default="Match Number", max_length=100),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.tournament",
                    ),
                ),
            ],
            options={
                "unique_together": {("tournament", "match_number")},
            },
        ),
    ]
