# Generated by Django 5.0.2 on 2024-03-16 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_customuser_groups_customuser_user_permissions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="registration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 16, 13, 46, 37, 152090, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="tournament_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 16, 13, 46, 37, 152291, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
