# Generated by Django 5.0.2 on 2024-03-16 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_alter_tournament_registration_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamstat",
            name="booyah",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="registration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 16, 14, 1, 57, 952246, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="tournament_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 16, 14, 1, 57, 952446, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
