# Generated by Django 5.0.2 on 2024-03-17 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_teamstat_booyah_alter_tournament_registration_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamstat",
            name="matches_played",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="teamstat",
            name="booyah",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="registration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 17, 14, 32, 11, 928448, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="tournament_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 17, 14, 32, 11, 928635, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
